version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "project.asgi:application"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app/backend
    command: ["python", "manage.py", "runworker"]