# Generated by Django 5.2.5 on 2025-08-08 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('bot_user', 'Bot User'), ('account_user', 'Account User')], max_length=20)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['telegram_user_id', 'type'], name='users_telegra_6fc161_idx')],
            },
        ),
    ]
