# Generated by Django 5.2.5 on 2025-08-08 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.BigIntegerField()),
                ('from_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('forwarded_from', models.BigIntegerField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('media_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_chats.chat')),
            ],
            options={
                'db_table': 'messages',
                'indexes': [models.Index(fields=['chat', 'created_at'], name='messages_chat_id_ec31ea_idx'), models.Index(fields=['chat', 'read'], name='messages_chat_id_f11848_idx'), models.Index(fields=['from_id'], name='messages_from_id_f1fafb_idx'), models.Index(fields=['message_id'], name='messages_message_83462e_idx')],
            },
        ),
    ]
