# Generated by Django 5.2.5 on 2025-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='commands',
            field=models.JSONField(blank=True, default=list, help_text='Bot commands list'),
        ),
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, help_text='Bot description (up to 512 characters)'),
        ),
        migrations.AddField(
            model_name='bot',
            name='first_name',
            field=models.CharField(blank=True, help_text="Bot's display name", max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='menu_button_text',
            field=models.CharField(blank=True, help_text='Menu button text', max_length=64),
        ),
        migrations.AddField(
            model_name='bot',
            name='menu_button_url',
            field=models.URLField(blank=True, help_text='Menu button URL'),
        ),
        migrations.AddField(
            model_name='bot',
            name='profile_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Bot profile photo', null=True, upload_to='bot_profiles/'),
        ),
        migrations.AddField(
            model_name='bot',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='Current profile photo URL from Telegram'),
        ),
        migrations.AddField(
            model_name='bot',
            name='profile_update_pending',
            field=models.BooleanField(default=False, help_text='Whether profile updates are pending'),
        ),
        migrations.AddField(
            model_name='bot',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for bot (up to 120 characters)', max_length=120),
        ),
    ]
