# Generated by Django 5.2.5 on 2025-08-08 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_accounts', '0001_initial'),
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bot_chat', 'Bot Chat'), ('account_chat', 'Account Chat')], max_length=20)),
                ('chat_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_accounts.account')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bots.bot')),
            ],
            options={
                'db_table': 'chats',
                'indexes': [models.Index(fields=['type', 'chat_id'], name='chats_type_0c1d2d_idx'), models.Index(fields=['bot', 'chat_id'], name='chats_bot_id_5c109f_idx'), models.Index(fields=['account', 'chat_id'], name='chats_account_a3032c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['bot_chat', 'account_chat'])), name='valid_chat_type')],
            },
        ),
    ]
