# Generated by Django 5.2.5 on 2025-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0001_initial'),
        ('telegram_bots', '0003_add_auto_reply'),
        ('telegram_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-last_message_at'], name='chats_last_me_0c3be9_idx'),
        ),
    ]
