# Generated by Django 5.2.5 on 2025-08-08 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tg_user_id', models.BigIntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('api_id_enc', models.TextField()),
                ('api_hash_enc', models.TextField()),
                ('session_enc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('login_required', 'Login Required')], default='inactive', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
